import type { Metadata } from "next";

import "./globals.css";
import './theme.css';
import ThemeProvider from '@/components/layout/ThemeToggle/theme-provider';
import { ActiveThemeProvider } from "@/components/active-theme";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          enableColorScheme
        >
          <ActiveThemeProvider>{children}</ActiveThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
